---
title: "Historical RRG health"
author: "Dana Lanceman"
date: "10/5/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/danal/OneDrive - UNSW/Desktop/Honours_UNSW/Assessment/cumbung_assessment')

library(sf)
library(raster)
library(exactextractr)
library(rgdal)
library(tidyverse)
```


```{r Load files}
cumbungBoundary <- st_read('raw/shp/Cumbung_ecological.shp')

# put all raster files in the folder into a list
files <- list.files(path = "C:/Users/danal/OneDrive - UNSW/Desktop/Honours_UNSW/Data_analysis/R_Studio/Project/Data_raw/raster/Inundation", pattern = "Inundation_")

files

#import all raster files in folder using lapply
setwd("C:/Users/danal/OneDrive - UNSW/Desktop/Honours_UNSW/Data_analysis/R_Studio/Project/Data_raw/raster/Inundation")
allrasters <- lapply(files, raster)
```


```{r Stack rasters and sum in 5 year intervals}
rs <- stack(allrasters)

# reclassify each to cells with presence/absence of water each year
rc <- reclassify(rs, c(0,0,0, 1,Inf,1)) # reclassify 0 to 0 and 1:infinity to 1




# sum each 5 years to determine number of years with water
r90 <- calc(rc[[c(1:5)]], fun=sum)
r91 <- calc(rc[[c(2:6)]], fun=sum)
r92 <- calc(rc[[c(3:7)]], fun=sum)
r93 <- calc(rc[[c(4:8)]], fun=sum)
r94 <- calc(rc[[c(5:9)]], fun=sum)
r95 <- calc(rc[[c(6:10)]], fun=sum)
r96 <- calc(rc[[c(7:11)]], fun=sum)
r97 <- calc(rc[[c(8:12)]], fun=sum)
r98 <- calc(rc[[c(9:13)]], fun=sum)
r99 <- calc(rc[[c(10:14)]], fun=sum)
r00 <- calc(rc[[c(11:15)]], fun=sum)
r01 <- calc(rc[[c(12:16)]], fun=sum)
r02 <- calc(rc[[c(13:17)]], fun=sum)
r03 <- calc(rc[[c(14:18)]], fun=sum)
r04 <- calc(rc[[c(15:19)]], fun=sum)
r05 <- calc(rc[[c(16:20)]], fun=sum)
r06 <- calc(rc[[c(17:21)]], fun=sum)
r07 <- calc(rc[[c(18:22)]], fun=sum)
r08 <- calc(rc[[c(19:23)]], fun=sum)
r09 <- calc(rc[[c(20:24)]], fun=sum)
r10 <- calc(rc[[c(21:25)]], fun=sum)
r11 <- calc(rc[[c(22:26)]], fun=sum)
r12 <- calc(rc[[c(23:27)]], fun=sum)
r13 <- calc(rc[[c(24:28)]], fun=sum)
r14 <- calc(rc[[c(25:29)]], fun=sum)
r15 <- calc(rc[[c(26:30)]], fun=sum)
r16 <- calc(rc[[c(27:31)]], fun=sum)
r17 <- calc(rc[[c(28:32)]], fun=sum)
r18 <- calc(rc[[c(27:33)]], fun=sum)
r19 <- calc(rc[[c(28:34)]], fun=sum)
r20 <- calc(rc[[c(29:35)]], fun=sum)

# try making a function for this
#for(i in 1:31){
#  assign(paste("r", i, sep = ""), calc(rs[[c(i:i+4)]], fun = sum))   
#}


# reclassify number of years inundated to mean RRG health

```

```{r it should be unnecessary to write the rasters}
data_names <- c("r90","r91","r92","r93","r94","r95","r96","r97","r98","r99","r00","r01","r02","r03","r04","r05","r06","r07","r08","r09","r10","r11","r12","r13","r14","r15","r16","r17","r18","r19","r20")


# write rasters
for(i in 1:length(data_names)) {                         
  writeRaster(get(data_names[i]),                              
             paste0("C:/Users/danal/OneDrive - UNSW/Desktop/Honours_UNSW/Assessment/cumbung_assessment/output/raster",
                    data_names[i],
                    ".tif"))
}

# for testing - only writing r90
setwd("C:/Users/danal/OneDrive - UNSW/Desktop/Honours_UNSW/Assessment/cumbung_assessment")
writeRaster(r90, "output/raster/r90.tif")
```

