---
title: "Water Level Bankfull Analysis"
author: "Dana Lanceman"
date: "11/26/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/danal/OneDrive - UNSW/Desktop/Honours_UNSW/Assessment/cumbung_assessment')
```

```{r get packages}
library(tidyverse)
library(readxl)
library(ggpubr)
```

```{r get data}
four <- read_excel("raw/water_level_discharge.xlsx", sheet = "four")
bool <- read_excel("raw/water_level_discharge.xlsx", sheet = "booligal")
yarra <- read_excel("raw/water_level_discharge.xlsx", sheet = "yarraman")
colig <- read_excel("raw/water_level_discharge.xlsx", sheet = "colignan")
red <- read_excel("raw/water_level_discharge.xlsx", sheet = "redbank")
oxley <- read_excel("raw/water_level_discharge.xlsx", sheet = "oxley")
renmark <- read_excel("raw/water_level_discharge.xlsx", sheet = "renmark")
willara <- read_excel("raw/water_level_discharge.xlsx", sheet = "willara")
cutta <- read_excel("raw/water_level_discharge.xlsx", sheet = "cuttaburra")
corrong <- read_excel("raw/water_level_discharge.xlsx", sheet = "corrong")
maude <- read_excel("raw/water_level_discharge.xlsx", sheet = "maude")


# not for bankfull analysis
barham <- read_excel("raw/water_level_discharge.xlsx", sheet = "barham")
hay <- read_excel("raw/water_level_discharge.xlsx", sheet = "hay")
flows2sa <- read_excel("raw/water_level_discharge.xlsx", sheet = "flows2sa")
```

```{r calculate average potential flood event interval}
# create a binary variable for above/below average water level
four <- four %>% mutate(abovemean = ifelse(Level >= mean(Level, na.rm = T), 1, 0))

# identify the start and end of each potential flood event and subset these 

# assign an index value to each pair of start/end dates

# put these indexes back on the original dataset 

# fill middle days in between start and end with the same index

# identify peaks from each continuous period of data - group by summarise max for each index

# for each index, filter to days that are above 50% of the peak

# then calculate the length of each interval

# then take the average interval length -> average potential flood event length
```

```{r calculate potential flood peaks}
# criteria: water level must drop below 75% of first peak before second peak, peaks must be at least the average potential flood length (calculated above) apart from each other

# create a binary variable for above/below average water level
four <- four %>% mutate(abovemean = ifelse(Level >= mean(Level, na.rm = T), 1, 0))

# create an empty vector to store potential peaks in
four$pot.peak <- numeric(4252)

# is each point higher than its immediate neighbours (before and after) - if yes, potential peak



# try on sample dataset
s <- tibble(x = c(1,2,3,2,1,2,4,4,3,2,3,1,2))

for(i in 2:length(s$x)){
  s$y[i] <- case_when((s$x[i] >= s$x[i+1]) & (s$x[i] >= s$x[i-1]) ~ 1,
  TRUE ~ 0)}

for(i in 1:4252){
  pot.peak[i] <- if_else(four$Level[i]>four$Level[i-1] & four$Level[i]>four$Level[i+1],1, 0)
}


for (i in 1:4252){
  if(i = c(1,4252)){
    four$pot.peak[i] = NULL
  } else if(!is.null(four$Level[i]) & !is.null(four$Level[i-1]) & !is.null(four$Level[i+1]) & four$Level[i]>four$Level[i-1] & four$Level[i]>four$Level[i+1]){
    four$pot.peak[i] = 1
  } else {
    four$pot.peak[i] = NULL
  }}


four <- four %>% 
  mutate(pot.peak = case_when(Level[i]>Level[i-1] & Level[i]>Level[i+1] ~ 1))


for(i in 1:4252){
  if_else(four$Level[i] > four$Level[i-1] && four$Level[i]>four$Level[i+1], print(1), print(0))
}



for(i in 2:length(four$Level)){
  four$pot.peak[i] <- case_when((four$Level[i] >= four$Level[i-1]) & 
                                  (four$Level[i] >= four$Level[i+1]) ~ 1,
                                TRUE ~ 0)
}





# index each peak 1, 2, 3 etc

# assign same index values between that peak and the next - fill and then round down to the nearest integer

# or assign peak/not peak column, then if(point = peak), find next point = peak, create a sequences of dates between these numbers - loop

# calculate 75% level of each peak

# column for true/false below 75% of the peak - for each index number

# take all rows between each pair of consecutive peaks, make a column 

```

