---
title: "Waterbirds"
author: "Dana Lanceman"
date: "8/23/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/danal/OneDrive - UNSW/Desktop/Honours_UNSW/Assessment/cumbung_assessment')
```

```{r setup}
library(tidyverse)
library(readxl)
library(viridis)
library(ggeffects)
library(ggpubr)

c <- read_excel("raw/waterbird_trends.xlsx", "cumbung") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
b <- read_excel("raw/waterbird_trends.xlsx", "booligal") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
g <- read_excel("raw/waterbird_trends.xlsx", "gwydir") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
m <- read_excel("raw/waterbird_trends.xlsx", "macquarie") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
r <- read_excel("raw/waterbird_trends.xlsx", "riverland") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
y <- read_excel("raw/waterbird_trends.xlsx", "yantabulla") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
p <- read_excel("raw/waterbird_trends.xlsx", "paroo") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
h <- read_excel("raw/waterbird_trends.xlsx", "hattah") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
l <- read_excel("raw/waterbird_trends.xlsx", "lowbidgee") %>% 
  mutate(ln.dis = log(Discharge),
         ln.bird = log(Waterbirds))
```


# Generalised linear models

Assumptions:
- Independance of each data points
- Correct distribution of the residuals (normal distribution of residuals)
- Correct specification of the variance structure (equal variances of residuals)
- Linear relationship between the response and the linear predictor


```{r function for plotting}
birdplot <- function(predict_data, title){
  plot(predict_data, facet = FALSE, colors = "hero", ci = T, dot.alpha = 1, dot.size = 5, add.data = TRUE, jitter = 0, show.y.title = T, show.title = FALSE) + 
  labs(x="",y="",title=title) +
  theme_bw() +
  geom_line(size = 1.2) +
  theme(text = element_text(size = 32), # change font size
        axis.text = element_text(size = 28),
        panel.grid.major = element_blank(), # remove grid lines
        panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5)) # centre title
}
```



```{r cumbung}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=c)
summary(M1)
cor.test(c$ln.bird, c$ln.dis)
# p = 0.0179

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(c$ln.dis,c$ln.bird) # linear relationship
# assumptions ok

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

cplot <- birdplot(ggemmeans.Inun, "Great Cumbung Swamp*")
cplot
```

```{r booligal}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=b)
summary(M1)
cor.test(b$ln.bird, b$ln.dis)
# p = 0.0142

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(b$ln.dis, b$ln.bird) # linear relationship
# assumptions ok, one outlier (2010 = 389000 waterbirds)

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

bplot <- birdplot(ggemmeans.Inun, "Booligal Wetlands*")
bplot
```

```{r gwydir}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=g)
summary(M1)
cor.test(g$ln.bird, g$ln.dis)
# p = 0.1766

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(g$ln.dis, g$ln.bird) # linear relationship
# assumptions seem ok

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

gplot <- birdplot(ggemmeans.Inun, "Gwydir Wetlands")
gplot
```

```{r hattah}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=h)
summary(M1)
cor.test(h$ln.bird, h$ln.dis)
# p = 0.1633

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(h$ln.dis,h$ln.bird) # linear relationship
# Assumtions seem ok

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

hplot <- birdplot(ggemmeans.Inun, "Hattah Lakes")
hplot
```

```{r lowbidgee}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=l)
summary(M1)
cor.test(l$ln.bird, l$ln.dis)
# p = 0.0233

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(l$ln.dis,l$ln.bird) # linear relationship
# assumptions seem ok

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

lplot <- birdplot(ggemmeans.Inun, "Lowbidgee Wetlands*")
lplot
```

```{r macquarie}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=m)
summary(M1)
cor.test(m$ln.bird, m$ln.dis)
# p = 0.000366

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(m$ln.dis,m$ln.bird) # linear relationship
# assumptions OK

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

mplot <- birdplot(ggemmeans.Inun, "Macquarie Marshes*")
mplot
```

```{r paroo}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=p)
summary(M1)
cor.test(p$ln.bird, p$ln.dis)
# p = 0.66976

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(p$ln.dis, p$ln.bird) # linear relationship
# assumptions OK

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

pplot <- birdplot(ggemmeans.Inun, "Paroo Overflow Swamps")
pplot
```

```{r riverland}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=r)
summary(M1)
cor.test(r$ln.bird, r$ln.dis)
# p = 0.348

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(r$ln.dis,r$ln.bird) # linear relationship
# assumptions ok

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

rplot <- birdplot(ggemmeans.Inun, "Murray Riverland Wetlands") +
  theme(title = element_text(size = 28)) # decrease title size for Murray Riverland
rplot
```

```{r yantabulla}
# generalised linear model
M1 <- glm(ln.bird ~ ln.dis, data=y)
summary(M1)
cor.test(y$ln.bird, y$ln.dis)
# p = 0.168, but only 4 data points

# check assumptions
par(mfrow = c(2, 2))
plot(M1) # top left equal variances, top right normality 
par(mfrow = c(1, 1))
plot(y$ln.dis, y$ln.bird) # linear relationship
# assumptions ok

# predict
ggemmeans.Inun <- ggemmeans(M1, terms = c("ln.dis[all]"))

yplot <- birdplot(ggemmeans.Inun, "Yantabulla Swamps")
yplot
```



```{r put plots together}
# export at 2100 x 2700 

bird <- ggarrange(cplot, bplot, lplot, mplot, gplot, yplot, pplot, rplot, hplot,
          #labels = c("A*", "B*", "C*", "D*", "E", "F", "G", "H", "I"),
          ncol = 3, nrow = 3,
          #hjust = -0.5, # moves plot labels right
          font.label = list(size = 40))

annotate_figure(bird, bottom = text_grob("Discharge (log-transformed)",  size = 60, just = "bottom"), left = text_grob("Waterbird abundance (log-transformed)", size = 60, rot = 90)) # rotate 90 degrees
# just = "bottom" helps text not be cut off
```

