---
title: "waterbird_drought"
author: "Dana Lanceman"
date: "8/27/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r set up}
library(tidyverse)
library(readxl)
library(viridis)
library(rstatix)
library(ggpubr)

# load MDB data
waterbird_MDB <- read.csv("raw/MDB2008-2024WaterbirdData20251003.csv") 

# summarise MDB by year, count 1 only
waterbird_MDB_Totals <- read.csv("raw/MDB2008-2024WaterbirdData20251003.csv") %>% subset(CountType != 2) %>% 
  group_by(SurvYear) %>% 
  summarise(Count = sum(Count)) 

# load cumbung data by year
waterbird_Cumbung_Totals <- read.csv("raw/WaterbirdSubset/CumbungWaterbirdTotalCount1.csv") %>% 
  select(SurvYear, Count) %>% 
  rename(CountCumbung = Count)

# merge datasets
waterbirdCumbungMDB <- left_join(waterbird_Cumbung_Totals, waterbird_MDB_Totals, by = "SurvYear")

# calculate the percentage of total waterbirds in the cumbung each year
waterbirdCumbungMDB <- waterbirdCumbungMDB %>% mutate(percentage_cumbung = CountCumbung/Count*100)

# append drought dataset - based on years with below average rainfall in the MDB https://www.bom.gov.au/climate/history/rainfall/
waterbirdCumbungMDB <- waterbirdCumbungMDB %>% mutate(drought = c("n", "n", "n", "y", "n", "n", "n", "y", "y", "y", "n", "n", "n", "y", "n"))
```


```{r  plot}
png("output2/birddrought.png", width = 1200, height = 700)
ggplot(waterbirdCumbungMDB, aes(drought,percentage_cumbung)) +
  geom_boxplot() +
  geom_jitter(size = 4) +
  labs(x = "", y = "% Waterbirds at  Great Cumbung Swamp") +
  scale_x_discrete(labels = c('Non-drought','Drought')) +
  theme_bw() + 
  theme(text = element_text(size = 32),
        axis.text = element_text(size = 28),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),)
dev.off()

```



Make sure to test assumptions!




```{r assumptions}
ggqqplot(waterbirdCumbungMDB, "percentage_cumbung")

par(mfrow = c(2, 2))
plot(waterbirdCumbungMDB)

ggplot(waterbirdCumbungMDB, aes(percentage_cumbung)) +
  geom_histogram(binwidth = 1)
```

```{r t test}
waterbirdCumbungMDB %>% t_test(percentage_cumbung~drought)
```

